export const ROLES = {
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
  MAHASISWA: "MAHASISWA",
  ADMIN_LPMI: "ADMIN_LPMI",
  OPERATOR_LPMI: "OPERATOR_LPMI",
  ALUMNI: "ALUMNI",
  DEKAN: "DEKAN",
  KAPRODI: "KAPRODI",
  DOSEN: "DOSEN",
  SEKRETARIS: "SEKRETARIS",
  REGISTER: "REGISTER",
};
