# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: filkomapp CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_IMAGES_PATH: ${{secrets.REACT_APP_IMAGES_PATH}}
      REACT_APP_BASE_URL_API: ${{secrets.REACT_APP_BASE_URL_API}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          buildArgs: REACT_APP_IMAGES_PATH=${{secrets.REACT_APP_IMAGES_PATH}}, REACT_APP_BASE_URL_API=${{secrets.REACT_APP_BASE_URL_API}}
          image: darellyuhu/filkomapp-fe
          tags: latest
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: docker-compose.yml
          target: ~/

      - name: SSH and run deploy docker compose script
        uses: appleboy/ssh-action@master
        env:
          REACT_APP_IMAGES_PATH: ${{secrets.REACT_APP_IMAGES_PATH}}
          REACT_APP_BASE_URL_API: ${{secrets.REACT_APP_BASE_URL_API}}
        with:
          command_timeout: 60m
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: REACT_APP_IMAGES_PATH, REACT_APP_BASE_URL_API
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d
