# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: filkomapp CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: filkomunklab/filkom-apps-fe:latest
          build-args: |
            DISABLE_ESLINT_PLUGIN=${{secrets.DISABLE_ESLINT_PLUGIN}}
            REACT_APP_IMAGES_PATH=${{secrets.REACT_APP_IMAGES_PATH}}
            REACT_APP_BASE_URL_API=${{secrets.REACT_APP_BASE_URL_API}}
            REACT_APP_OBE_BASE_URL_API=${{secrets.REACT_APP_OBE_BASE_URL_API}}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v4
      - name: Copy Docker Compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./docker-compose.yml"
          target: fe

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd fe
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d
